### ISSUE TITLE
Review action fails

### ISSUE THREAD

**Issue by LeviLovie** [mbrobbel/rustfmt-check#1154]
I'm using your project to format code on pull request. Here is the action file (same as in README.md):
```yaml
on: pull_request

name: Rustfmt

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
```

Here is the error I'm getting from the [run](https://github.com/LeviLovie/pinniped/actions/runs/12174998979/job/33958022201):
```
Error: Unprocessable Entity: "Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank" - https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request
```

I feel like I'm doing something wrong. Thank you for the action :).
Here is the [pr](https://github.com/LeviLovie/pinniped/pull/3)
