### ISSUE TITLE
Action failing with Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by tsetso-spread** [mbrobbel/rustfmt-check#1212]
Hello and thank you for developing this action!
As of today I've noticed that our builds that use `rustfmt-check` have started failing with: `Error: Cannot find module 'tslib'`
Last successful run was from 26th February 4pm UTC, has not been run since.

Full logs:

```txt
Run mbrobbel/rustfmt-check@master
  with:
    token: ***
    mode: commit
    commit-message: Format Rust code using rustfmt
  env:
    CARGO_HOME: /home/runner/.cargo
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
node:internal/modules/cjs/loader:1[2](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:2)28
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /home/runner/work/_actions/mbrobbel/rustfmt-check/master/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1[3](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:3)11:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/_actions/mbrobbel/rustfmt-check/master/dist/index.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1[4](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:4)69:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1[5](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:5)48:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:1[7](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:7)4:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/mbrobbel/rustfmt-check/master/dist/index.js'
  ]
}

Node.js v20.1[8](https://github.com/spread-ai/nextgen-xmap/actions/runs/13718000222/job/38367898618#step:4:8).0
```

My setup is as follows:

```yaml
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  checks: write
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
